version: "3"
services:
  postgres:
    container_name: rss-rush
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
